name: loggen
dependencies:
    test: any
    html: any
    collection: any
transformers:
- $dart2js:
    checked: true
    minify: true
    terse: true
    verbose: true
    commandLineOptions: [--show-package-warnings]
